### PR TITLE
Added contact section pop up

### PR DESCRIPTION
**Pull request by saisumanthkumar**
Screenshot (158)

@garimasingh128 please look into it

### CODE REVIEW

**Comment by garimasingh128** [comment]
Looks good!
Changes I would suggest:
1. Github username to be garimasingh128 instead of garysingh128
2. Change base branch to develop

Thanks.

**Comment by saisumanthkumar** [comment]
@garimasingh128 Done ,please check it

**Comment by saisumanthkumar** [comment]
@garimasingh128 a small request from my side ,It would be helpful if you add `hacktoberfest-accepted` label to this current PR

Thank you!!!

**Comment by saisumanthkumar** [comment]
@garimasingh128 according to oss port , the label should be `hacktoberfest-accepted`,the first letter should be small
please update the label name 

thanks!! In advance

**Pull request merged**
